name: Strife
version: ${project.version}
main: land.face.strife.StrifePlugin
api-version: 1.16
depend: [Facecore, ProtocolLib]
softdepend: [Loot, Bullion, LibsDisguises, SnazzyParties, DiscordSRV, HeadDatabase, XGlow, HolographicDisplays]

commands:
  cast:
    aliases: [ability-macro]
  stats:
    aliases: [st]
  inspect:
    aliases: [look]
  levelup:
    aliases: [lu]
  strife:
    aliases: [str]
  spawner:
    aliases: [spn]
  agility:
    aliases: [agi]

permissions:
  strife.stats:
    default: true
  strife.cast:
    default: true
  strife.levelup:
    default: true
  strife.reset:
    default: op
  strife.clear:
    default: op
  strife.raise:
    default: op
  strife.addxp:
    default: op
  strife.spawner:
    default: op
  strife.reload:
    default: op
  strife.xp:
    default: false